FROM python:3

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

ENV APP /app

RUN mkdir $APP
WORKDIR $APP

EXPOSE 9999

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .